#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

// xiaoXiong_4G board configuration

#include <driver/gpio.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE true
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_48
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_14
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_46

#define AUDIO_CODEC_GPIO_PA GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_2
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_38
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define XIAOXIONG_ENABLE_EYE_RENDER 1

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define GC9A01_SPI1_LCD_GPIO_SCLK (GPIO_NUM_41)
#define GC9A01_SPI1_LCD_GPIO_MOSI (GPIO_NUM_42)
#define GC9A01_SPI1_LCD_GPIO_RST (GPIO_NUM_45)
#define GC9A01_SPI1_LCD_GPIO_DC (GPIO_NUM_1)
#define GC9A01_SPI1_LCD_GPIO_CS (GPIO_NUM_40)
#define GC9A01_SPI1_LCD_GPIO_BL (GPIO_NUM_NC)
#define GC9A01_SPI1_LCD_GPIO_MISO (GPIO_NUM_NC)

#define GC9A01_SPI2_LCD_GPIO_SCLK (GPIO_NUM_41)
#define GC9A01_SPI2_LCD_GPIO_MOSI (GPIO_NUM_42)
#define GC9A01_SPI2_LCD_GPIO_RST (GPIO_NUM_45)
#define GC9A01_SPI2_LCD_GPIO_DC (GPIO_NUM_1)
#define GC9A01_SPI2_LCD_GPIO_CS (GPIO_NUM_39)
#define GC9A01_SPI2_LCD_GPIO_BL (GPIO_NUM_NC)
#define GC9A01_SPI2_LCD_GPIO_MISO (GPIO_NUM_NC)

#define GC9A01_LCD_SPI1_NUM (SPI2_HOST)
#define GC9A01_LCD_SPI2_NUM (SPI2_HOST)
#define GC9A01_LCD_PIXEL_CLK_HZ (20 * 1000 * 1000)
#define GC9A01_LCD_CMD_BITS (8)
#define GC9A01_LCD_PARAM_BITS (8)
#define GC9A01_LCD_COLOR_SPACE (ESP_LCD_COLOR_SPACE_RGB)
#define GC9A01_LCD_BITS_PER_PIXEL (16)
#define GC9A01_LCD_DRAW_BUFF_DOUBLE (1)
#define GC9A01_LCD_DRAW_BUFF_HEIGHT (240)
#define GC9A01_LCD_BL_ON_LEVEL (1)

#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 160
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_SPI_SCLK_HZ (40 * 1000 * 1000)

#define XIAOXIONG_ENABLE_CAMERA 1

// camera

/* Camera pins */
#define CAMERA_PIN_PWDN -1
#define CAMERA_PIN_RESET -1
#define CAMERA_PIN_XCLK GPIO_NUM_16
#define CAMERA_PIN_SIOD GPIO_NUM_4
#define CAMERA_PIN_SIOC GPIO_NUM_5

#define CAMERA_PIN_D7 GPIO_NUM_15
#define CAMERA_PIN_D6 GPIO_NUM_17
#define CAMERA_PIN_D5 GPIO_NUM_18
#define CAMERA_PIN_D4 GPIO_NUM_47
#define CAMERA_PIN_D3 GPIO_NUM_10
#define CAMERA_PIN_D2 GPIO_NUM_3
#define CAMERA_PIN_D1 GPIO_NUM_9
#define CAMERA_PIN_D0 GPIO_NUM_21
#define CAMERA_PIN_VSYNC GPIO_NUM_6
#define CAMERA_PIN_HREF GPIO_NUM_7
#define CAMERA_PIN_PCLK GPIO_NUM_8

#define XCLK_FREQ_HZ 20000000

// ML307 uses UART1 inside the esp-ml307 component, so keep the toy MCU on UART2.
#define TOY_SERVO_UART_PORT_NUM UART_NUM_2
#define TOY_SERVO_UART_BAUD_RATE (115200)
#define TOY_SERVO_UART_TXD GPIO_NUM_43
#define TOY_SERVO_UART_RXD GPIO_NUM_44

#define TOY_SERVO_UART_RTS GPIO_NUM_NC
#define TOY_SERVO_UART_CTS GPIO_NUM_NC
#define TOY_SERVO_RX_TIMEOUT_MS 20

#define ML307_RX_PIN GPIO_NUM_11
#define ML307_TX_PIN GPIO_NUM_12
#define ML307_DTR_PIN GPIO_NUM_NC

#endif  // _BOARD_CONFIG_H_
